import { StyleSheet } from "react-native";

export const globalStyles = (isDarkMode) =>
  StyleSheet.create({
    container: {
      padding: 20,
      backgroundColor: isDarkMode ? "#181818" : "#f2f9ff",
      flex: 1,
    },
    formContainer: {
      padding: 10,
      alignItems: "center",
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      borderTopWidth: 4,
      borderTopColor: "#36A9E1",
      width: "100%",
      backgroundColor: "#062E56",
    },
    button: {
      backgroundColor: "#fff",
      borderRadius: 20,
      paddingVertical: 10,
      paddingHorizontal: 15,
      alignItems: "center",
      marginVertical: 20,
    },
    buttonText: {
      color: "black",
      fontWeight: "600",
      fontSize: 16,
    },
    label: {
      marginBottom: 5,
      fontWeight: "400",
      fontSize: 14,
      color: "#fff",
      userSelect: "none",
    },
    input: {
      width: 300,
      paddingVertical: 5,
      paddingHorizontal: 20,
      borderRadius: 20,
      backgroundColor: "#AEBBC7",
      borderWidth: 0,
      marginBottom: 20,
      fontStyle: "italic",
    },
    image: {
      width: 100,
      height: 100,
      borderRadius: 5,
      margin: 10,
    },
    content: {
      flex: 1,
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    titleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
    },
    title: {
      fontSize: 16,
      fontWeight: "bold",
      color: isDarkMode ? "black" : "white",
      flexWrap: "wrap",
      flexShrink: 1,
    },
    iconDetail: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 1,
      gap: 5,
    },
    detailsContainer: {
      backgroundColor: isDarkMode ? "#004E9C" : "#001529",
      padding: 10,
      marginBottom: 10,
      borderRadius: 10,
      justifyContent: "space-around",
    },

    timeText: {
      fontSize: 14,
      color: "white",
    },
    description: {
      fontSize: 14,
      color: "#7f8c8d",
      marginTop: 5,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
      width: "90%",
      maxHeight: "80%",
      padding: 20,
      borderRadius: 10,
      backgroundColor: "white",
    },
    titleContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "bold",
    },
    details: {
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      marginBottom: 10,
    },
    errorText: {
      color: "red",
      fontSize: 14,
    },
    successText: {
      color: "green",
      fontSize: 14,
    },
    bottomContainer: {
      padding: 10,
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      backgroundColor: "#001529",
      minHeight: 60,
    },
    footer: {
      width: "100%",
      paddingHorizontal: 20,
      paddingBottom: 20,
      alignItems: "center",
    },
    logoutText: {
      fontSize: 16,
      fontWeight: "bold",
      textDecorationLine: "underline",
      color: isDarkMode ? "white" : "black",
    },
    text: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 20,
      color: isDarkMode ? "white" : "black",
    },
    categoryContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 20,
      marginBottom: 10,
    },
    categoryButton: {
      width: 120,
      height: 50,
      padding: 10,
      borderTopRightRadius: 10,
      borderBottomRightRadius: 10,
      backgroundColor: isDarkMode ? "#004E9C" : "#062E56",
      alignItems: "center",
      justifyContent: "center",
    },
    showAll: {
      width: "100%",
      height: 30,
      backgroundColor: isDarkMode ? "#004E9C" : "#062E56",
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    category: {
      color: "#e0efff",
      fontSize: 16,
    },
    iconContainer: {
      width: 50,
      height: 50,
      backgroundColor: isDarkMode ? "#062E56" : "#001529",
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    division: {
      height: 1,
      width: "70%",
      backgroundColor: isDarkMode ? "white" : "#062E56",
    },
    recipeContainer: {
      borderRadius: 10,
      borderColor: isDarkMode ? "white" : "#062E56",
      borderWidth: 1,
      minHeight: 230,
      width: 150,
      alignItems: "center",
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    loadingText: {
      marginTop: 10,
      fontSize: 16,
      color: "#3478a1",
    },
    header: {
      backgroundColor: isDarkMode ? "#062E56" : "#E5FFFF",
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderBottomColor: isDarkMode ? "#36A9E1" : "#062E56",
      borderBottomWidth: 4,
      alignItems: "center",
    },
    logo: {
      width: 200,
      height: 50,
      marginRight: 10,
    },
    headerView: {
      flexDirection: "row",
      alignItems: "center",
    },
    scrollViewContent: {
      paddingTop: 10,
    },
    filterLabel: {
      fontSize: 16,
      fontWeight: "bold",
      marginVertical: 10,
    },
    checkboxContainer: {
      marginBottom: 10,
      paddingLeft: 0,
    },
    checkboxText: {
      fontSize: 16,
    },
    emptyText: {
      textAlign: "center",
      fontSize: 16,
      color: "#7f8c8d",
      marginTop: 20,
    },
    recipeCard: {
      marginBottom: 20,
      backgroundColor: isDarkMode ? "white" : "#001529",
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
      borderLeftColor: isDarkMode ? "#36A9E1" : "#062E56",
      borderLeftWidth: 7,
      flexDirection: "row",
      height: 120,
      position: "relative",
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    bookmarkContainer: {
      position: "absolute",
      bottom: 10,
      right: 10,
    },
    imageDetail: {
      width: "100%",
      height: 200,
      borderRadius: 10,
      marginBottom: 20,
    },
    titleDetail: {
      fontSize: 24,
      fontWeight: "bold",
      marginBottom: 10,
      color: isDarkMode ? "white" : "black",
    },
    descriptionDetail: {
      fontSize: 16,
      marginBottom: 20,
      color: isDarkMode ? "white" : "black",
    },
    stepNumberContainer: {
      marginRight: 20,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#36A9E1",
      width: 30,
      height: 30,
      borderRadius: 100,
    },
    stepNumber: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#001529",
    },
    stepTextContainer: {
      flex: 1,
    },
    stepText: {
      fontSize: 16,
      flexWrap: "wrap",
      color: isDarkMode ? "white" : "black",
    },
    floatingButton: {
      position: "absolute",
      bottom: 20,
      right: 20,
      backgroundColor: "#36A9E1",
      borderRadius: 30,
      width: 50,
      height: 50,
      justifyContent: "center",
      alignItems: "center",
      elevation: 5,
    },
    modalItem: {
      marginBottom: 10,
    },
    closeButton: {
      marginTop: 20,
      backgroundColor: "#36A9E1",
      padding: 10,
      borderRadius: 5,
      alignItems: "center",
    },
    closeButtonText: {
      color: "white",
      fontWeight: "bold",
    },
  });
