import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: "#f2f9ff",
    flex: 1,
  },
  headerText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F4EFE8",
  },
  formContainer: {
    padding: 10,
    alignItems: "center",
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderTopWidth: 4,
    borderTopColor: "#36A9E1",
    width: "100%",
    backgroundColor: "#062E56",
  },
  rowCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginVertical: 10,
    backgroundColor: "#D9C7B2",
    borderRadius: 5,
    borderLeftWidth: 4,
    borderLeftColor: "#8B5E3C",
    width: "100%",
  },
  rowCardText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#5B3B1E",
  },
  iconContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  button: {
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: "center",
    marginVertical: 20,
  },
  buttonText: {
    color: "black",
    fontWeight: "600",
    fontSize: 16,
  },
  label: {
    marginBottom: 5,
    fontWeight: "400",
    fontSize: 14,
    color: "#fff",
    userSelect: "none",
  },
  input: {
    width: 300,
    paddingVertical: 5,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: "#AEBBC7",
    borderWidth: 0,
    marginBottom: 20,
    fontStyle: "italic"
  },
  card: {
    backgroundColor: "#D9C7B2",
    borderRadius: 5,
    padding: 15,
    marginVertical: 5,
    marginHorizontal: 10,
    borderColor: "#8B5E3C",
    borderWidth: 2,
  },
  cardText: {
    fontSize: 14,
    color: "#2c3e50",
  },
  image: {
    width: 100,
    height: 100,
    borderRadius: 5,
    margin: 10,
  },
  content: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
    flexWrap: "wrap",
    flexShrink: 1,
  },
  iconDetail: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 1,
    gap: 5,
  },
  detailsContainer: {
    backgroundColor: "#E4E4E4",
    padding: 10,
    marginBottom: 10,
    borderRadius: 10,
    justifyContent: "space-around",
  },

  timeText: {
    fontSize: 14,
    color: "white",
  },
  description: {
    fontSize: 14,
    color: "#7f8c8d",
    marginTop: 5,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    width: "80%",
    maxHeight: "80%",
    padding: 20,
    borderRadius: 10,
    backgroundColor: "white",
    justifyContent: "flex-start",
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  details: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: 10,
  },
  errorText: {
    color: "red",
    fontSize: 14,
  },
  successText: {
    color: "green",
    fontSize: 14,
  },
  bottomContainer: {
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    backgroundColor: "#001529",
    minHeight: 60,
  },
});
