export const recipes = [
  {
    titulo: "Pão com ovo e queijo",
    slider: false,
    destaque: false,
    imagem:
      "https://www.receiteria.com.br/wp-content/uploads/pao-com-ovo-e-queijo-na-airfryer-1.jpg",
    categoria: "Café",
    dificuldade: "Fácil",
    favorito: false,
    descricao:
      "O Pão com Ovo e Queijo é uma receita simples e deliciosa, perfeita para o café da manhã. Feito com pão francês, ovos e queijo mussarela, é preparado na airfryer, ficando crocante por fora e cremoso por dentro. Rápido, fácil e saboroso!",
    tempo: 15,
    porcao: 1,
    ingredientes: {
      "Pão francês": 1,
      "Ovos médios": 2,
      "Fatias de queijo mussarela": 2,
      "Sal e pimenta-do-reino": "a gosto",
      "Orégano ou salsinha desidratada": "a gosto",
      AirFryer: 1,
    },
    passos: {
      1: "Separe os ingredientes para fazer o pão com ovo e queijo na airfryer. Preaqueça a airfryer a 180ºC por cerca de 5 minutos.",
      2: "Corte o pão ao meio, na horizontal. Com as pontas dos dedos ou com uma colher, pressione o miolo dentro dos pães para que forme uma cavidade mais funda.",
      3: "Quebre os ovos e coloque cuidadosamente dentro dos pães, um ovo em cada banda de pão.",
      4: "Tempere os ovos com sal, pimenta-do-reino e orégano. Acomode as fatias de mussarela por cima dos ovos temperados.",
      5: "Leve para a airfryer a 180ºC por cerca de 7 a 9 minutos, ou até dourar o queijo.",
      6: "Sirva no café da manhã e comece o dia muito bem.",
    },
  },
  {
    titulo: "Pão de Queijo",
    slider: true,
    destaque: false,
    imagem:
      "https://www.receiteria.com.br/wp-content/uploads/pao-de-queijo-de-liquidificador-facil.jpg",
    categoria: "Café",
    dificuldade: "Fácil",
    favorito: false,
    descricao:
      "O Pão de Queijo é uma verdadeira delícia, com uma crosta dourada e um interior macio e levemente puxento. Seu sabor é irresistível, combinando o toque suave do queijo com a leve acidez do polvilho. Perfeito para acompanhar um café fresquinho, esse quitute é ideal para quem busca um momento de conforto e sabor a qualquer hora do dia.",
    tempo: 25,
    porcao: 12,
    ingredientes: {
      "Polvilho azedo (xícaras)": 2,
      "Ovo médio": 1,
      "Óleo (xícaras)": 0.5,
      "Leite (xícaras)": 1,
      "Sal (colher de chá)": 1,
      "Mussarela (gramas)": 200,
      Liquidificador: 1,
      Forminhas: 1,
      Forno: 1,
    },
    passos: {
      1: "Quebre o ovo em uma xícara para verificar se ele não está estragado, em seguida, despeje no liquidificador desligado.",
      2: "Bata a mistura no liquidificador por 2 minutos.",
      3: "Unte forminhas de cupcake e preaqueça o forno a 200 ºC por 10 minutos.",
      4: "Despeje 2 colheres de sopa da massa do liquidificador em cada forminha.",
      5: "Leve ao forno preaquecido por cerca de 25 minutos ou até a massa crescer e ficar douradinha.",
      6: "Sirva o pão de queijo quentinho!",
    },
  },
  {
    titulo: "Bolo de Caneca de Chocolate",
    slider: false,
    destaque: true,
    imagem:
      "https://static.itdg.com.br/images/640-400/5ea64abff4dd7fb5a02d915cbad8c85a/332617-original.jpg",
    categoria: "Café",
    dificuldade: "Fácil",
    favorito: false,
    descricao:
      "Prepare-se para uma experiência rápida e deliciosa com este bolo de caneca de micro-ondas! Com apenas alguns minutos e uma canequinha, você poderá desfrutar de um saboroso e reconfortante bolo individual.",
    tempo: 10,
    porcao: 1,
    ingredientes: {
      "Açúcar (colheres de sopa)": 3,
      Ovo: 1,
      "Óleo (colher de sopa)": 1,
      "Leite (colheres de sopa)": 4,
      "Farinha de trigo (colheres de sopa)": 4,
      "Achocolatado em pó (colheres de sopa)": 2,
      "Fermento em pó (colher de café)": 1,
      Caneca: 1,
      "Micro-ondas": 1,
    },
    passos: {
      1: "Coloque todos os ingredientes dentro de uma caneca de aproximadamente 300 ml ou mais.",
      2: "Mexa até obter uma massa homogênea e leve ao micro-ondas por 3 minutos.",
      3: "Para a calda, misture todos os ingredientes em uma panela, aqueça em fogo médio e mexa até engrossar.",
      4: "Despeje a calda sobre o bolo assim que retirá-lo do micro-ondas.",
    },
  },

  {
    titulo: "Dadinho de Tapioca",
    slider: false,
    destaque: true,
    imagem:
      "https://receitas.wap.ind.br/wp-content/uploads/2024/08/dadinho-de-tapioca-1080x640.jpg",
    categoria: "Acompanhamento",
    dificuldade: "Fácil",
    favorito: false,
    descricao:
      "Um petisco delicioso de boteco que fica perfeito com uma geleia de pimenta, aprenda como fazer dadinho de tapioca!",
    tempo: 90,
    porcao: 30,
    ingredientes: {
      "Farinha de tapioca granulada": "500g",
      "Queijo coalho ralado": "500g",
      "Pimenta-do-reino e sal": "a gosto",
      "Leite líquido integral": "1L",
      "Geleia agridoce de pimenta": "a gosto",
      Assadeira: 1,
      "Colher de silicone": 1,
      Panela: 1,
      Faca: 1,
    },
    passos: {
      1: "Aqueça o leite em uma panela.",
      2: "Quando o leite estiver bem quente, desligue o fogo, adicione o queijo coalho ralado e continue mexendo.",
      3: "Logo em seguida adicione a farinha de tapioca granulada e continue mexendo.",
      4: "Adicione o sal e pimenta a gosto.",
      5: "Pare de mexer quando todos os ingredientes estiverem bem misturados.",
      6: "Despeje em uma forma coberta com papel filme (PVC), cubra em cima também e leve para a geladeira por duas horas.",
      7: "Depois retire da geladeira, corte em quadradinhos (dadinhos) e frite aos poucos em óleo quente ou coloque no forno até dourar.",
      8: "Sirva em seguida acompanhado da geleia de pimenta agridoce.",
    },
  },
  {
    titulo: "Batata Suíça",
    slider: true,
    destaque: false,
    imagem:
      "https://static.itdg.com.br/images/640-400/e9f2d8649a9f1c74d8b2f06347a9f777/49942-original.jpg",
    categoria: "Acompanhamento",
    dificuldade: "Fácil",
    favorito: false,
    descricao:
      "São batatas raladas com preparo especial, grelhadas por fora e muito recheadas por dentro.",
    tempo: 15,
    porcao: 4,
    ingredientes: {
      Batatas: "250g",
      Manteiga: "para untar a frigideira",
      "Vasilha com água e sal": "para umedecer os dedos",
      "Sugestões de recheio": [
        "Queijo cremoso, mussarela, carne seca",
        "Queijo cremoso, mussarela, estrogonofe grosso",
        "Queijo cremoso, mussarela, camarão",
      ],
    },
    passos: {
      1: "Leve as batatas para cozinhar em uma panela com água.",
      2: "Quando começar a ferver, marque 7 minutos e retire as batatas.",
      3: "Leve para geladeira e deixe de um dia para o outro.",
      4: "Retire da geladeira e passe no ralo grosso.",
      5: "Unte uma frigideira de 16 cm de diâmetro com manteiga.",
      6: "Coloque a batata ralada, o suficiente para cobrir o fundo da frigideira, sempre umedecendo as mãos na água com sal (facilita o manuseio da batata e salga ao mesmo tempo).",
      7: "Ponha também uma camada do recheio desejado, quantidade para cobrir a batata, deixando as bordas livres.",
      8: "Depois, coloque mais uma camada de batata e leve ao fogo médio por mais ou menos 3 minutos.",
      9: "Pegue outra frigideira também untada, vire e deixe mais 3 minutos deste lado.",
      10: "Repita o processo mais duas vezes ou até dourar a batata.",
    },
  },
  {
    titulo: "Ketchup Caseiro",
    slider: false,
    destaque: false,
    imagem:
      "https://static.itdg.com.br/images/640-400/fa66a94344dd1a342d994902b2afba09/shutterstock-1779861296-1-.jpg",
    categoria: "Acompanhamento",
    dificuldade: "Fácil",
    favorito: false,
    descricao:
      "Desvende o segredo de um ketchup caseiro, preparado com ingredientes básicos e frescos em apenas alguns minutos.",
    tempo: 5,
    porcao: 1,
    ingredientes: {
      "Extrato de tomate": "4 colheres (chá)",
      Vinagre: "3 colheres (chá)",
      Açúcar: "4 colheres (chá)",
      Sal: "3 colheres (chá)",
    },
    passos: {
      1: "Junte todos os ingredientes em um recipiente.",
      2: "Bata bem até obter uma consistência homogênea.",
    },
  },
  {
    titulo: "Tiramisu",
    slider: false,
    destaque: true,
    imagem:
      "https://br.giallozafferano.com/images/5-598/Tiramisu_650x433_wm.jpg",
    categoria: "Doce",
    dificuldade: "Médio",
    favorito: false,
    descricao:
      "O tiramisu italiano é uma das joias da culinária do país, uma sobremesa envolvente e inigualável que conquista paladares ao redor do mundo.",
    tempo: 300,
    porcao: 15,
    ingredientes: {
      "Clara em neve": "6 unidades",
      "Leite condensado": "1/2 lata",
      "Biscoito tipo champagne (sem açúcar)": "1 pacote",
      "Licor (chocolate, café, amêndoa ou conhaque)": "1 dose pequena",
      "Gemas peneiradas": "6 unidades",
      "Queijo tipo mascarpone": "500g",
      "Café bem forte (sem açúcar)": "1 xícara",
      "Chocolate em pó": "para polvilhar",
      Vasilha: 1,
      Refratário: 1,
      "Plástico filme": 1,
    },
    passos: {
      1: "Em uma vasilha grande, misture gentilmente o queijo e o leite condensado, acrescente as gemas peneiradas até formar um creme meio amarelado claro.",
      2: "Em seguida, acrescente as claras, mas não misture muito.",
      3: "O segredo da receita é a paciência. Misture bem suave e reserve este creme.",
      4: "Em outra vasilha, coloque o café e o licor de sua preferência e molhe o biscoito bem rapidamente no café. O biscoito não pode estar muito molhado.",
      5: "Disponha em um refratário retangular.",
      6: "Monte 1 camada de biscoito, 1 camada de creme, e finalize com uma camada de creme. Polvilhe o chocolate em pó por cima.",
      7: "Leve à geladeira coberto com plástico filme por mais ou menos 6 horas.",
    },
  },
  {
    titulo: "Macaron",
    slider: false,
    destaque: false,
    imagem:
      "https://static.itdg.com.br/images/1200-675/06edb6a571a067e7c6029dbde006d1b5/275301-original.jpg",
    categoria: "Doce",
    dificuldade: "Médio",
    favorito: false,
    descricao:
      "O macaron é um doce francês superdelicado e delicioso que ganhou o coração dos brasileiros!",
    tempo: 60,
    porcao: 6,
    ingredientes: {
      "Açúcar cristal": "36g",
      "Açúcar de confeiteiro": "36g",
      "Clara de ovo": "36g",
      "Farinha de amêndoa": "42g",
      "Saco plástico": 1,
      Tesoura: 1,
      "Papel manteiga": 1,
      Assadeira: 1,
    },
    passos: {
      1: "Peneire a farinha de amêndoa com o açúcar de confeiteiro duas vezes.",
      2: "Bata as claras em neve em velocidade média.",
      3: "Adicione metade do açúcar cristal e bata mais um pouco.",
      4: "Adicione o restante e bata por 8 minutos.",
      5: "Coloque o corante desejado para dar a cor de seu macaron e bata por mais 1 minuto.",
      6: "Acrescente a farinha de amêndoa e misture suavemente.",
      7: "Coloque a massa em um saquinho plástico e corte a ponta.",
      8: "Em uma forma com papel-manteiga, faça pequenas bolinhas afastadas umas das outras.",
      9: "Deixe secar por 20 a 30 minutos.",
      10: "Asse em forno a 140°C por cerca de 13 minutos.",
      11: "Deixe de 1 a 2 minutos no forno desligado.",
      12: "Desenforme os disquinhos e junte dois a dois.",
      13: "Recheie com doce de leite ou outro creme de sua preferência.",
    },
  },
  {
    titulo: "Cookies",
    slider: true,
    destaque: false,
    imagem: "https://i.panelinha.com.br/i1/bk-3044-blog-ayu2251.webp",
    categoria: "Doce",
    dificuldade: "Médio",
    favorito: false,
    descricao:
      "O cookie é uma verdadeira obra-prima, combinando crocância externa com maciez interna, garantindo uma explosão de sabor a cada mordida.",
    tempo: 40,
    porcao: 22,
    ingredientes: {
      "Manteiga sem sal (temperatura ambiente)": "125g",
      "Açúcar mascavo": "1/2 xícara",
      "Farinha de trigo": "1 3/4 xícara",
      "Chocolate meio amargo picado": "300g",
      "Chocolate em pó": "1/4 xícara",
      Açúcar: "3/4 xícara",
      Ovo: "1",
      "Fermento em pó": "1 colher (chá)",
      "Essência de baunilha": "1 colher (chá)",
      Assadeira: 1,
      Espátula: 1,
      Bandeja: 1,
      Tigela: 1,
    },
    passos: {
      1: "Misture a manteiga, açúcar mascavo, açúcar, essência de baunilha e chocolate em pó (se for usar).",
      2: "Adicione o ovo batido aos poucos e misture bem.",
      3: "Acrescente a farinha aos poucos e misture bem (na mão ou na batedeira planetária).",
      4: "Por último, adicione o fermento e misture só para incorporá-lo à massa.",
      5: "Depois da massa bem misturada, adicione o chocolate picado.",
      6: "Forme bolinhas pequenas e asse em forno preaquecido sobre papel-manteiga por aproximadamente 15 a 20 minutos (250°C).",
    },
  },

  {
    titulo: "Risoto de Camarão",
    slider: false,
    destaque: false,
    imagem:
      "https://s2-receitas.glbimg.com/_BJ2faGHrU_peYyRsFYyA7YaBSY=/0x0:1366x768/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2024/U/i/zqZlTfTke4oUrxuhixVA/risoto-basico.jpg",
    categoria: "Principal",
    dificuldade: "Médio",
    favorito: false,
    descricao:
      "O risoto é um prato da culinária italiana à base de arroz que você pode fazer em casa sem ter muito trabalho.",
    tempo: 50,
    porcao: 4,
    ingredientes: {
      "Camarão cinza limpo": "400g",
      "Caldo de camarão": "1 cubo",
      "Tomate sem sementes e cortado em cubos pequenos": "1 unidade",
      "Extrato de tomate": "2 colheres de sopa",
      Azeite: "1 colher de sopa",
      Limão: "1/2 unidade",
      "Arroz branco": "3 xícaras de chá",
      "Pimentão verde cortado em cubos pequenos": "1/2 xícara de chá",
      "Dente de alho": "2 unidades",
      Sal: "a gosto",
    },
    passos: {
      1: "Tempere o camarão com limão e sal, reserve por 10 minutos.",
      2: "Enquanto isso, faça o arroz, fritando-o muito bem.",
      3: "Adicione água suficiente para cobrir o arroz (cerca de 2 cm acima do nível do arroz) e cozinhe em fogo baixo até secar.",
      4: "Retire do fogo e deixe a tampa aberta para o arroz não passar do ponto.",
      5: "Em uma frigideira grande, doure o alho no azeite e adicione os camarões sem o suco do limão.",
      6: "Junte o tomate, o pimentão, o extrato de tomate e o cubo de caldo de camarão.",
      7: "Adicione água para formar um molho que cubra os camarões e cozinhe por 5 minutos em fogo baixo.",
      8: "Misture o arroz ao molho de camarão com cuidado e sirva.",
    },
  },
  {
    titulo: "Yakisoba",
    slider: false,
    destaque: true,
    imagem:
      "https://static.itdg.com.br/images/640-400/b77169a959b9d32180b11fd952ec5519/shutterstock-1183796671-1-1-.jpg",
    categoria: "Principal",
    dificuldade: "Fácil",
    favorito: false,
    descricao:
      "Originário da culinária chinesa e popularizado no Japão, o yakisoba é um prato que conquistou paladares ao redor do mundo, tornando-se uma iguaria apreciada por sua combinação única de sabores, texturas e aromas.",
    tempo: 40,
    porcao: 4,
    ingredientes: {
      Espaguete: "300g",
      Óleo: "1 colher de sopa",
      "Couve-flor": "1 maço pequeno",
      "Carne cortada em tiras": "400g",
      "Cenoura cortada em rodelas": "1 unidade",
      "Amido de milho": "1 colher de sopa (dissolvido em 50 ml de água)",
      "Cebola cortada em pedaços médios": "1 unidade",
      Brócolis: "1/2 maço pequeno",
      "Molho shoyu": "10 colheres de sopa",
      Champignon: "100g",
      Acelga: "a gosto",
      Água: "250ml",
    },
    passos: {
      1: "Cozinhe o macarrão em ponto al dente e reserve.",
      2: "Em uma panela, aqueça o óleo e refogue a cebola e a carne.",
      3: "Adicione o molho shoyu e cozinhe por 3 minutos.",
      4: "Acrescente a água e, ao levantar fervura, adicione o amido de milho dissolvido.",
      5: "Mexa até engrossar, abaixe o fogo e adicione o champignon, a couve-flor, o brócolis e a cenoura.",
      6: "Cozinhe por 8 minutos e acrescente a acelga e o macarrão.",
      7: "Misture bem, ajuste o sal e tampe a panela por mais 1 minuto.",
      8: "Sirva em seguida.",
    },
  },
  {
    titulo: "Strogonoff de Carne",
    slider: false,
    destaque: false,
    imagem:
      "https://static.itdg.com.br/images/640-400/816e0de0719daaddd0a48ff4977a4f55/254282-320433-original.jpg",
    categoria: "Principal",
    dificuldade: "Fácil",
    favorito: false,
    descricao:
      "O strogonoff de carne é um clássico que agrada a todos. Esta receita, simples e cheia de sabores intensos, oferece uma experiência gastronômica que cativa os paladares mais exigentes.",
    tempo: 30,
    porcao: 8,
    ingredientes: {
      "Carne (patinho ou coxão mole)": "1kg",
      "Champignon ou palmito": "1 vidro",
      "Pimenta-do-reino": "a gosto",
      "Tomates picados sem pele e sementes": "3 unidades",
      Ketchup: "2 colheres de sopa",
      "Cebolas médias": "3 unidades",
      Sal: "a gosto",
      "Creme de leite": "2 latas",
      "Óleo de oliva": "3 colheres de sopa",
      "Caldo de carne (dissolvido em 100 ml de água)": "1 cubo",
    },
    passos: {
      1: "Em uma panela, aqueça o óleo e refogue a carne com a cebola, os tomates e o caldo de carne. Cozinhe por 20 minutos.",
      2: "Adicione o ketchup e o champignon e cozinhe até formar um molho consistente.",
      3: "Desligue o fogo e acrescente o creme de leite sem soro, misturando bem.",
      4: "Sirva em uma travessa decorada com temperos e batata palha.",
    },
  },
  {
    titulo: "Bolo Red Velvet",
    slider: true,
    destaque: false,
    imagem:
      "https://www.receitasnestle.com.br/sites/default/files/srh_recipes/4f012df686c9759da04453742d8f3360.jpg",
    categoria: "Doce",
    dificuldade: "Difícil",
    favorito: false,
    descricao:
      "O Bolo Red Velvet é um bolo de textura muito leve e macia (aveludada), de sabor amanteigado, e a chocolate ainda que muito ao de leve, e com o travozinho ácido que o caracteriza. De cor avermelhada, ganha ainda mais destaque em contraste com o recheio e cobertura de creme de queijo branco.",
    tempo: 100,
    porcao: 15,
    ingredientes: {
      " Manteiga": "3 colheres de sopa",
      Ovos: "4 unidades",
      "Chocolate em pó": "2 e 1/2 colheres de sopa",
      "Farinha de trigo": "1 xícara e 1/2 colher de sopa",
      "Vinagre branco": "1/2 colher de sopa",
      "Leite aquecido": "100 ml",
      "Corante vermelho em gel": "1 e 1/2 colher de sopa",
      Açúcar: "1 e 1/4 xícara",
      "Fermento em pó": "1/2 colher de sopa",
      Água: "4 colheres de sopa",
      "Cream cheese": "1 e 1/2 xícara",
      "Açúcar de confeiteiro": "4 e 1/2 xícaras",
      "gelatina sem sabor": "12g",
      manteiga: "3/4 xícara",
      "essência de baunilha": "1/2 colher de café",
      Batedeira: 1,
    },
    passos: {
      1: "Despeje o leite já aquecido na panela, acrescente a manteiga e misture",
      2: "Coloque o chocolate em pó e deixe em fogo médio até a manteiga derreter completamente.",
      3: "Desligue o fogo, coloque o corante, misture e reserve.",
      4: "Na batedeira, despeje os ovos e o açúcar e bata até dobrar de volume.",
      5: "Acrescente o vinagre e bata por mais 3 minutos.",
      6: "Adicione o farinha e o fermento e misture bem.",
      7: "Depois, acrescente a mistura com a corante aos poucos e mexa mais.",
      8: "Despeje a massa numa forma redonda e leve ao forno preaquecido a 180 graus por 40 minutos.",
      9: "Para fazer o recheio, em um recipiente, coloque a água, a gelatina e misture.",
      10: "Na batedeira, despeje o cream cheese, a manteiga e bata até ficar cremoso.",
      11: "Acrescente o açúcar de confeiteiro peneirado, a essência de baunilha e bata mais.",
      12: "Despeje a gelatina hidratada, bata mais e depois reserve na geladeira.",
      13: "Corte o bolo em 3 camadas.",
      14: "Disponha uma camada num prato e coloque uma parte do recheio.",
      15: "Coloque outra camada, mais recheio e outra camada de bolo.",
      16: "Cubra o bolo com um pouco do recheio e coloque frutas vermelhas de sua preferência, como morangos e cerejas.",
    },
  },

  {
    titulo: "Sushi",
    slider: false,
    destaque: false,
    imagem:
      "https://terramar.com.br/media/terramar/2024/04/Saiba-onde-comer-sushi-em-Novo-Hamburgo.jpg",
    categoria: "Principal",
    dificuldade: "Difícil",
    favorito: false,
    descricao:
      "O sushi é um prato da culinária japonesa que possui origem numa antiga técnica de conservação da carne de peixe em arroz avinagrado. O sushi, na forma em que é conhecido atualmente, tem cerca de 200 anos; inicialmente, era vendido em barracas, como comida de rua, numa espécie de fast food.",
    tempo: 60,
    porcao: 15,
    ingredientes: {
      "Arroz japonês": "4 xícaras",
      "Vinagre de arroz para sushi": "4 colheres de sopa",
      Pepino: "2 unidades",
      "Tirinhas de salmão": "",
      Água: "5 xícaras",
      "Pacote e algas desidratadas": "1 unidade",
      cenoura: "2 unidades",
      "Folhas de alface": "",
      "Saquê doce mirin": "2 colheres de sopa",
      Sal: "2 colheres de chá",
      "Açúcar branco": "4 colheres de chá",
      "Wasabi em pasta": "",
      Esteira: 1,
      Tigela: 1,
      "Plástico Filme": 1,
    },
    passos: {
      1: "Corte os pepinos e as cenouras em tiras e deixe em molho na água com uma pitada de sal.",
      2: "Faça o arroz temperado com o sal.",
      3: "Para o tempero do arroz misture em uma tigela o saquê mirin, açúcar branco, sal e wasabi(se desejar)",
      4: "Transfira o arroz cozido para uma tigela grande.",
      5: "As poucos acrescente o molho de sushi, com a ajuda de uma colher de pau vire o arroz, sem mexer muito.",
      6: "Deixe esfriar",
      7: "Forre a esteira para sushi com o plástico filme.",
      8: "Coloque folha de alga com a parte mais áspera para cima.",
      9: "Umedeça a palma das mãos para o arroz não grudar.",
      10: "Preencha a alga com uma camada de arroz de mais ou menos 1 cm uniformemente, comece pelo meio da alga e espalhe, lembrando sempre de deixar 1 cm de sobra da alga para ter uma finalização elegante.",
      11: "Após isso espalhe um um pouco de wasabi no centro do arroz de ponta a ponta (lembrando que wasabi é forte), a quantidade de um grão de feijão é o suficiente.",
      12: "Coloque 1 tira de pepino, 1 de cenoura, 1 de salmão e 1 folha de alface.",
      13: "Enrole com o auxilio da esteira e com a ponta dos dedos como se fosse um rocambole, lembrando de tirar a esteira conforme a alga cola no arroz.",
      14: "No final passe um pouco de água na alga e cole na própria",
      15: "Mergulhe a faca no copo com água e corte em rolinhos em um único corte para não amassar o sushi, comece cortando pelo centro,assim eles ficarão da mesma altura.",
      16: "Coloque em uma travessa e decore a seu gosto.",
      17: "Sirva com um pequeno prato de molho shoyu.",
    },
  },
];
